### ISSUE TITLE
All in one

### ISSUE THREAD

**Issue by ang1243** [harrystech/prelaunchr#26]
Is there a way of making all of the different files into one file, so you can just copy and paste the code into a html reader, so it is easy for stupid, inexperienced RoR people like me?

**Comment by ckhatton** [comment]
Na, I really don't think that possible at all - It renders HTML for the browser to interpret, but I think I understand what you mean. For this to work you have to upload it to a server that you own or something like Heroku, or run it locally off your computer.

With a rails environment already set up (making sure you use the same Rails version as in the Gemfile and PostgreSQL), it is a matter of...
* downloading the zip and exporting it into a folder
* running a 'bundle install' within the folder
* starting up the Rails server within the folder

:octocat:

**Comment by BillyParadise** [comment]
If only it was that easy.  I'm at 99% now, fighting with delayedjob now.  

2015-02-15T19:49:41-0500: [Worker(delayed_job host:rails02.xx.xx pid:1666)] Class#signup_email failed with ActionView::Template::Error: undefined method `encoding' for {:host=>"xxx"}:Hash - 3 failed attempts

Unfortunately I came to Rails after 4.0, so all these 3.x'isms are causing me to relearn a lot of things.
