### ISSUE TITLE
Upgrade to Rails 4

### ISSUE THREAD

**Issue by aaronlerch** [harrystech/prelaunchr#5]
I've got a branch where I did an upgrade of the app to Rails 4. I don't know that you want to merge it into `master` directly, but if you create a branch for rails 4 I'd be happy to issue a pull request into that branch.

Or if you prefer to update the app to rails 4 by default (probably reasonably safe) then I'm happy to do a pull request directly to `master`.

Or of course you can access my repo and merge it in yourself any way you like. :)
Thanks!

**Comment by ckhatton** [comment]
Hi @danielschwartz 
I know you are busy, but can someone commit these pull requests, and also start committing the other pull requests, they are starting to pile up. I would like the fork the project, and especially use the Rails4 branch. Please add me as a contributor if you do not have the time. Thanks
:octocat:

**Comment by danielschwartz** [comment]
@ckhatton we've unfortunately abandoned supporting this project. We'd be happy for you to fork it to a separate repo and become the owner of it, as long as you remove our assets from it. 

We just don't have time to support this specific project in addition to all our other open source endeavors. Sorry!

**Comment by ckhatton** [comment]
@danielschwartz Okay that is fine - I will fork it and see if I can take on the pull requests (which I have never done and not sure is possible to a forked repo) :8ball:

**Comment by wardpenney** [comment]
I've done it over at https://github.com/wardpenney/prelaunchr

I need to remove the assets, but it is Rails 4.2, Ruby 2.2.0

**Comment by ckhatton** [comment]
Noice! :+1:

Are you able to also add the outstanding pull requests?

**Comment by irubnich** [comment]
Done
