### ISSUE TITLE
Working App???

### ISSUE THREAD

**Issue by deehill** [harrystech/prelaunchr#56]
Has anyone managed to get this working??

What version of Ruby/DB/OS?

Thanks

**Comment by ckhatton** [comment]
I haven't tried it with the latest version of Rails, but it definitely works on older versions if you can't get it working with the latest version of Rails.

:shipit:

**Comment by deehill** [comment]
Hey Chris.

I sent you a reply to your contact email. If you can can you hit me via my email!

Thanks

**Comment by ckhatton** [comment]
Can someone please close this issue? It is a question whether the app generally works, rather than point out an issue with the current version.

**Comment by vivek2007** [comment]
if you go to the homepage and sign up, you'll get your personal link. If you then sign in from another device with the same email you can not see your link / progress.

**Comment by nodox** [comment]
@deehill Thanks for raising an issue!

As @ckhatton stated try to keep issues to specific problems that you are having with the application.
When we keep issues to specific problems its makes easier for us to help you.

**Comment by vivek2007** [comment]
how can i see my progress after signup

if you go to the homepage and sign up, you'll get your personal link. If you then sign in from another device with the same email you can not see your link / progress.

**Comment by vivek2007** [comment]
if you go to the homepage and sign up, you'll get your personal link. If
you then sign in from another device with the same email you can not see
your link / progress.
