### ISSUE TITLE
How to change json version for prelaunchr?

### ISSUE THREAD

**Issue by prabhjas** [harrystech/prelaunchr#66]
Because currently, it requires JSON 1.7.7 Version. But that doesn't works with a recent version of Rails.
Please help..

**Comment by ckhatton** [comment]
Edit the version in the gemfile??

**Comment by prabhjas** [comment]
source 'https://rubygems.org'

gem 'rails', '3.2.11'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'pg'

gem 'activeadmin'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

group :development do
  gem 'pry'
end

gem 'delayed_job_active_record'

gem 'unicorn'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'

**Comment by prabhjas** [comment]
Above code doesn't contains JSON version.

**Comment by ckhatton** [comment]
There was not need to paste out the gemfile.

If it's not there, then it will be in your global gemset for your computer/server.

Look online for a guide on how to upgrade it stuck.

**Comment by prabhjas** [comment]
Hey, I've got it. It's in gemfile.lock ?
Thanks.

**Comment by ckhatton** [comment]
The `gemfile.lock` is generated when you use `bundle install`. So whatever you change in there will be overwritten.
